version: '3'
services:
    nginx:
        build: docker/nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/app
    php:
        build: docker/php-fpm
        volumes:
            - ./:/app
        working_dir: /app
    nodejs:
        build: docker/nodejs
        volumes:
            - ./:/app
        working_dir: /app
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
