version: '3'
services:
    app:
        build: docker/php-fpm
        volumes:
            - .:/var/www/app
        working_dir: /var/www/app
        depends_on:
          - node
    nginx:
        build: docker/nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/app
    node:
        build: docker/nodejs
        volumes:
            - .:/var/www/app
    redis:
        image: redis:latest
        ports:
            - "6379:6379"



